version: '2'
services:
  comments:
    build: ./comments
    container_name: comment-ms
    depends_on:
      - db
    links:
      - db
    ports:
      - "4100:4100"
    #   - MONGO_URI=127.0.0.1:27018
    network_mode: "host"
  db:
    image: mongo:3.3
    container_name: comment-db
    command: mongod --port 27018
    ports:
      - "27018:27018"
    # environment:
    #   - MONGO_URI=127.0.0.1:27018
    network_mode: "host"