version: '2'
services:
  comment-ms:
    build: ./comments
    # container_name: comment_ms
    depends_on:
      - comment-db
    links:
      - comment-db
    ports:
      - "4100:4100"
  comment-db:
    image: mongo:3.3
    # container_name: comment_db
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw